# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RequestPivot(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'pivots': 'list[RequestPivot]'
    }

    attribute_map = {
        'key': 'key',
        'pivots': 'pivots'
    }

    def __init__(self, key=None, pivots=None):  # noqa: E501
        """RequestPivot - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._pivots = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if pivots is not None:
            self.pivots = pivots

    @property
    def key(self):
        """Gets the key of this RequestPivot.  # noqa: E501

        A key corresponding to a matching field facet label or stats.  # noqa: E501

        :return: The key of this RequestPivot.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this RequestPivot.

        A key corresponding to a matching field facet label or stats.  # noqa: E501

        :param key: The key of this RequestPivot.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def pivots(self):
        """Gets the pivots of this RequestPivot.  # noqa: E501


        :return: The pivots of this RequestPivot.  # noqa: E501
        :rtype: list[RequestPivot]
        """
        return self._pivots

    @pivots.setter
    def pivots(self, pivots):
        """Sets the pivots of this RequestPivot.


        :param pivots: The pivots of this RequestPivot.  # noqa: E501
        :type: list[RequestPivot]
        """

        self._pivots = pivots

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestPivot, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestPivot):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
