# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RequestQuery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'language': 'str',
        'query': 'str',
        'user_query': 'str'
    }

    attribute_map = {
        'language': 'language',
        'query': 'query',
        'user_query': 'userQuery'
    }

    def __init__(self, language='afts', query=None, user_query=None):  # noqa: E501
        """RequestQuery - a model defined in Swagger"""  # noqa: E501
        self._language = None
        self._query = None
        self._user_query = None
        self.discriminator = None
        if language is not None:
            self.language = language
        self.query = query
        if user_query is not None:
            self.user_query = user_query

    @property
    def language(self):
        """Gets the language of this RequestQuery.  # noqa: E501

        The query language in which the query is written.  # noqa: E501

        :return: The language of this RequestQuery.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this RequestQuery.

        The query language in which the query is written.  # noqa: E501

        :param language: The language of this RequestQuery.  # noqa: E501
        :type: str
        """
        allowed_values = ["afts", "lucene", "cmis"]  # noqa: E501
        if language not in allowed_values:
            raise ValueError(
                "Invalid value for `language` ({0}), must be one of {1}"  # noqa: E501
                .format(language, allowed_values)
            )

        self._language = language

    @property
    def query(self):
        """Gets the query of this RequestQuery.  # noqa: E501

        The query which may have been generated in some way from the userQuery  # noqa: E501

        :return: The query of this RequestQuery.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this RequestQuery.

        The query which may have been generated in some way from the userQuery  # noqa: E501

        :param query: The query of this RequestQuery.  # noqa: E501
        :type: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    @property
    def user_query(self):
        """Gets the user_query of this RequestQuery.  # noqa: E501

        The exact search request typed in by the user  # noqa: E501

        :return: The user_query of this RequestQuery.  # noqa: E501
        :rtype: str
        """
        return self._user_query

    @user_query.setter
    def user_query(self, user_query):
        """Sets the user_query of this RequestQuery.

        The exact search request typed in by the user  # noqa: E501

        :param user_query: The user_query of this RequestQuery.  # noqa: E501
        :type: str
        """

        self._user_query = user_query

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestQuery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
