# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RequestFilterQueriesInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'query': 'str',
        'tags': 'list[str]'
    }

    attribute_map = {
        'query': 'query',
        'tags': 'tags'
    }

    def __init__(self, query=None, tags=None):  # noqa: E501
        """RequestFilterQueriesInner - a model defined in Swagger"""  # noqa: E501
        self._query = None
        self._tags = None
        self.discriminator = None
        if query is not None:
            self.query = query
        if tags is not None:
            self.tags = tags

    @property
    def query(self):
        """Gets the query of this RequestFilterQueriesInner.  # noqa: E501

        The filter query expression. For multi-select facets selected facets must be order together   # noqa: E501

        :return: The query of this RequestFilterQueriesInner.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this RequestFilterQueriesInner.

        The filter query expression. For multi-select facets selected facets must be order together   # noqa: E501

        :param query: The query of this RequestFilterQueriesInner.  # noqa: E501
        :type: str
        """

        self._query = query

    @property
    def tags(self):
        """Gets the tags of this RequestFilterQueriesInner.  # noqa: E501

        Tags used exclude the filters from facet evaluation for multi-select facet support  # noqa: E501

        :return: The tags of this RequestFilterQueriesInner.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this RequestFilterQueriesInner.

        Tags used exclude the filters from facet evaluation for multi-select facet support  # noqa: E501

        :param tags: The tags of this RequestFilterQueriesInner.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestFilterQueriesInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestFilterQueriesInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
