# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RequestHighlight(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fields': 'list[RequestHighlightFields]',
        'fragment_size': 'int',
        'max_analyzed_chars': 'int',
        'merge_contiguous': 'bool',
        'postfix': 'str',
        'prefix': 'str',
        'snippet_count': 'int',
        'use_phrase_highlighter': 'bool'
    }

    attribute_map = {
        'fields': 'fields',
        'fragment_size': 'fragmentSize',
        'max_analyzed_chars': 'maxAnalyzedChars',
        'merge_contiguous': 'mergeContiguous',
        'postfix': 'postfix',
        'prefix': 'prefix',
        'snippet_count': 'snippetCount',
        'use_phrase_highlighter': 'usePhraseHighlighter'
    }

    def __init__(self, fields=None, fragment_size=None, max_analyzed_chars=None, merge_contiguous=None, postfix=None, prefix=None, snippet_count=None, use_phrase_highlighter=None):  # noqa: E501
        """RequestHighlight - a model defined in Swagger"""  # noqa: E501
        self._fields = None
        self._fragment_size = None
        self._max_analyzed_chars = None
        self._merge_contiguous = None
        self._postfix = None
        self._prefix = None
        self._snippet_count = None
        self._use_phrase_highlighter = None
        self.discriminator = None
        if fields is not None:
            self.fields = fields
        if fragment_size is not None:
            self.fragment_size = fragment_size
        if max_analyzed_chars is not None:
            self.max_analyzed_chars = max_analyzed_chars
        if merge_contiguous is not None:
            self.merge_contiguous = merge_contiguous
        if postfix is not None:
            self.postfix = postfix
        if prefix is not None:
            self.prefix = prefix
        if snippet_count is not None:
            self.snippet_count = snippet_count
        if use_phrase_highlighter is not None:
            self.use_phrase_highlighter = use_phrase_highlighter

    @property
    def fields(self):
        """Gets the fields of this RequestHighlight.  # noqa: E501

        The fields to highlight and field specific configuration properties for each field  # noqa: E501

        :return: The fields of this RequestHighlight.  # noqa: E501
        :rtype: list[RequestHighlightFields]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this RequestHighlight.

        The fields to highlight and field specific configuration properties for each field  # noqa: E501

        :param fields: The fields of this RequestHighlight.  # noqa: E501
        :type: list[RequestHighlightFields]
        """

        self._fields = fields

    @property
    def fragment_size(self):
        """Gets the fragment_size of this RequestHighlight.  # noqa: E501

        The character length of each snippet.  # noqa: E501

        :return: The fragment_size of this RequestHighlight.  # noqa: E501
        :rtype: int
        """
        return self._fragment_size

    @fragment_size.setter
    def fragment_size(self, fragment_size):
        """Sets the fragment_size of this RequestHighlight.

        The character length of each snippet.  # noqa: E501

        :param fragment_size: The fragment_size of this RequestHighlight.  # noqa: E501
        :type: int
        """

        self._fragment_size = fragment_size

    @property
    def max_analyzed_chars(self):
        """Gets the max_analyzed_chars of this RequestHighlight.  # noqa: E501

        The number of characters to be considered for highlighting. Matches after this count will not be shown.  # noqa: E501

        :return: The max_analyzed_chars of this RequestHighlight.  # noqa: E501
        :rtype: int
        """
        return self._max_analyzed_chars

    @max_analyzed_chars.setter
    def max_analyzed_chars(self, max_analyzed_chars):
        """Sets the max_analyzed_chars of this RequestHighlight.

        The number of characters to be considered for highlighting. Matches after this count will not be shown.  # noqa: E501

        :param max_analyzed_chars: The max_analyzed_chars of this RequestHighlight.  # noqa: E501
        :type: int
        """

        self._max_analyzed_chars = max_analyzed_chars

    @property
    def merge_contiguous(self):
        """Gets the merge_contiguous of this RequestHighlight.  # noqa: E501

        If fragments over lap they can be  merged into one larger fragment  # noqa: E501

        :return: The merge_contiguous of this RequestHighlight.  # noqa: E501
        :rtype: bool
        """
        return self._merge_contiguous

    @merge_contiguous.setter
    def merge_contiguous(self, merge_contiguous):
        """Sets the merge_contiguous of this RequestHighlight.

        If fragments over lap they can be  merged into one larger fragment  # noqa: E501

        :param merge_contiguous: The merge_contiguous of this RequestHighlight.  # noqa: E501
        :type: bool
        """

        self._merge_contiguous = merge_contiguous

    @property
    def postfix(self):
        """Gets the postfix of this RequestHighlight.  # noqa: E501

        The string used to mark the end of a highlight in a fragment.  # noqa: E501

        :return: The postfix of this RequestHighlight.  # noqa: E501
        :rtype: str
        """
        return self._postfix

    @postfix.setter
    def postfix(self, postfix):
        """Sets the postfix of this RequestHighlight.

        The string used to mark the end of a highlight in a fragment.  # noqa: E501

        :param postfix: The postfix of this RequestHighlight.  # noqa: E501
        :type: str
        """

        self._postfix = postfix

    @property
    def prefix(self):
        """Gets the prefix of this RequestHighlight.  # noqa: E501

        The string used to mark the start of a highlight in a fragment.  # noqa: E501

        :return: The prefix of this RequestHighlight.  # noqa: E501
        :rtype: str
        """
        return self._prefix

    @prefix.setter
    def prefix(self, prefix):
        """Sets the prefix of this RequestHighlight.

        The string used to mark the start of a highlight in a fragment.  # noqa: E501

        :param prefix: The prefix of this RequestHighlight.  # noqa: E501
        :type: str
        """

        self._prefix = prefix

    @property
    def snippet_count(self):
        """Gets the snippet_count of this RequestHighlight.  # noqa: E501

        The maximum number of distinct highlight snippets to return for each highlight field.  # noqa: E501

        :return: The snippet_count of this RequestHighlight.  # noqa: E501
        :rtype: int
        """
        return self._snippet_count

    @snippet_count.setter
    def snippet_count(self, snippet_count):
        """Sets the snippet_count of this RequestHighlight.

        The maximum number of distinct highlight snippets to return for each highlight field.  # noqa: E501

        :param snippet_count: The snippet_count of this RequestHighlight.  # noqa: E501
        :type: int
        """

        self._snippet_count = snippet_count

    @property
    def use_phrase_highlighter(self):
        """Gets the use_phrase_highlighter of this RequestHighlight.  # noqa: E501

        Should phrases be identified.  # noqa: E501

        :return: The use_phrase_highlighter of this RequestHighlight.  # noqa: E501
        :rtype: bool
        """
        return self._use_phrase_highlighter

    @use_phrase_highlighter.setter
    def use_phrase_highlighter(self, use_phrase_highlighter):
        """Sets the use_phrase_highlighter of this RequestHighlight.

        Should phrases be identified.  # noqa: E501

        :param use_phrase_highlighter: The use_phrase_highlighter of this RequestHighlight.  # noqa: E501
        :type: bool
        """

        self._use_phrase_highlighter = use_phrase_highlighter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestHighlight, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestHighlight):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
