# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RequestLimits(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'permission_evaluation_count': 'int',
        'permission_evaluation_time': 'int'
    }

    attribute_map = {
        'permission_evaluation_count': 'permissionEvaluationCount',
        'permission_evaluation_time': 'permissionEvaluationTime'
    }

    def __init__(self, permission_evaluation_count=None, permission_evaluation_time=None):  # noqa: E501
        """RequestLimits - a model defined in Swagger"""  # noqa: E501
        self._permission_evaluation_count = None
        self._permission_evaluation_time = None
        self.discriminator = None
        if permission_evaluation_count is not None:
            self.permission_evaluation_count = permission_evaluation_count
        if permission_evaluation_time is not None:
            self.permission_evaluation_time = permission_evaluation_time

    @property
    def permission_evaluation_count(self):
        """Gets the permission_evaluation_count of this RequestLimits.  # noqa: E501

        Maximum count of post query permission evaluations  # noqa: E501

        :return: The permission_evaluation_count of this RequestLimits.  # noqa: E501
        :rtype: int
        """
        return self._permission_evaluation_count

    @permission_evaluation_count.setter
    def permission_evaluation_count(self, permission_evaluation_count):
        """Sets the permission_evaluation_count of this RequestLimits.

        Maximum count of post query permission evaluations  # noqa: E501

        :param permission_evaluation_count: The permission_evaluation_count of this RequestLimits.  # noqa: E501
        :type: int
        """

        self._permission_evaluation_count = permission_evaluation_count

    @property
    def permission_evaluation_time(self):
        """Gets the permission_evaluation_time of this RequestLimits.  # noqa: E501

        Maximum time for post query permission evaluation  # noqa: E501

        :return: The permission_evaluation_time of this RequestLimits.  # noqa: E501
        :rtype: int
        """
        return self._permission_evaluation_time

    @permission_evaluation_time.setter
    def permission_evaluation_time(self, permission_evaluation_time):
        """Sets the permission_evaluation_time of this RequestLimits.

        Maximum time for post query permission evaluation  # noqa: E501

        :param permission_evaluation_time: The permission_evaluation_time of this RequestLimits.  # noqa: E501
        :type: int
        """

        self._permission_evaluation_time = permission_evaluation_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestLimits, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestLimits):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
