# coding: utf-8

# flake8: noqa

"""
    Alfresco Content Services REST API

    **Discovery API**  Provides access to information about Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from .api.discovery_api import DiscoveryApi
# import ApiClient
from .api_client import ApiClient
from .configuration import Configuration
# import models into sdk package
from .models.discovery_entry import DiscoveryEntry
from .models.entitlements_info import EntitlementsInfo
from .models.error import Error
from .models.error_error import ErrorError
from .models.license_info import LicenseInfo
from .models.module_info import ModuleInfo
from .models.repository_entry import RepositoryEntry
from .models.repository_info import RepositoryInfo
from .models.status_info import StatusInfo
from .models.version_info import VersionInfo
