openapi: 3.0.0
info:
  description: |
    **Authentication API**

    Provides access to the authentication features of Alfresco Content Services.
  title: Alfresco Content Services REST API
  version: "1"
paths:
  /tickets:
    post:
      description: >
        **Note:** this endpoint is available in Alfresco 5.2 and newer versions.


        Logs in and returns the new authentication ticket.


        The userId and password properties are mandatory in the request body. For example:

        ```JSON

        {
            "userId": "jbloggs",
            "password": "password"
        }

        ```

        To use the ticket in future requests you should pass it in the request header.

        For example using Javascript:
          ```Javascript
            request.setRequestHeader ("Authorization", "Basic " + btoa(ticket));
          ```
      operationId: createTicket
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TicketBody"
        description: The user credential.
        required: true
      responses:
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TicketEntry"
        "400":
          description: |
            **userId** or **password** is not provided
        "403":
          description: Login failed
        "501":
          description: SAML is enabled and enforced
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Create ticket (login)
      tags:
        - authentication
      x-alfresco-since: "5.2"
  /tickets/-me-:
    delete:
      description: |
        **Note:** this endpoint is available in Alfresco 5.2 and newer versions.

        Deletes logged in ticket (logout).
      operationId: deleteTicket
      responses:
        "204":
          description: Successful response
        "400":
          description: URL path does not include **-me-** or the ticket is not provided by
            the Authorization header
        "404":
          description: Status of the user has changed (for example, the user is locked or
            the account is disabled) or the ticket has expired
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Delete ticket (logout)
      tags:
        - authentication
      x-alfresco-since: "5.2"
    get:
      description: >
        **Note:** this endpoint is available in Alfresco 5.2 and newer versions.


        Validates the specified ticket (derived from Authorization header) is still valid.


        For example, you can pass the Authorization request header using Javascript:
          ```Javascript
            request.setRequestHeader ("Authorization", "Basic " + btoa(ticket));
          ```
      operationId: validateTicket
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidTicketEntry"
        "400":
          description: URL path does not include **-me-** or the ticket is not provided by
            the Authorization header
        "401":
          description: Authentication failed
        "404":
          description: The request is authorized correctly but the status of the user (of
            the supplied ticket) has changed (for example, the user is locked or
            the account is disabled) or the ticket has expired
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Validate ticket
      tags:
        - authentication
      x-alfresco-since: "5.2"
security:
  - basicAuth: []
servers:
  - url: /alfresco/api/-default-/public/authentication/versions/1
components:
  securitySchemes:
    basicAuth:
      description: HTTP Basic Authentication
      type: http
      scheme: basic
  schemas:
    Error:
      properties:
        error:
          properties:
            briefSummary:
              type: string
            descriptionURL:
              type: string
            errorKey:
              type: string
            logId:
              type: string
            stackTrace:
              type: string
            statusCode:
              format: int32
              type: integer
          type: object
      required:
        - error
      type: object
    Ticket:
      properties:
        id:
          type: string
        userId:
          type: string
      type: object
    TicketBody:
      properties:
        password:
          type: string
        userId:
          type: string
      type: object
    TicketEntry:
      properties:
        entry:
          $ref: "#/components/schemas/Ticket"
      required:
        - entry
      type: object
    ValidTicket:
      properties:
        id:
          type: string
      type: object
    ValidTicketEntry:
      properties:
        entry:
          $ref: "#/components/schemas/ValidTicket"
      required:
        - entry
      type: object
