# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from alfresco_workflow_client.models.person import Person
from typing import Optional, Set
from typing_extensions import Self

class Item(BaseModel):
    """
    A process item. 
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    created_by: Optional[Person] = Field(default=None, alias="createdBy")
    description: Optional[StrictStr] = None
    edited: Optional[StrictBool] = None
    id: Optional[StrictStr] = None
    mime_type: Optional[StrictStr] = Field(default=None, alias="mimeType")
    modified_at: Optional[datetime] = Field(default=None, alias="modifiedAt")
    modified_by: Optional[Person] = Field(default=None, alias="modifiedBy")
    name: Optional[StrictStr] = None
    size: Optional[StrictInt] = None
    title: Optional[StrictStr] = None
    value: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["createdAt", "createdBy", "description", "edited", "id", "mimeType", "modifiedAt", "modifiedBy", "name", "size", "title", "value"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Item from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of modified_by
        if self.modified_by:
            _dict['modifiedBy'] = self.modified_by.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Item from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "createdBy": Person.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "description": obj.get("description"),
            "edited": obj.get("edited"),
            "id": obj.get("id"),
            "mimeType": obj.get("mimeType"),
            "modifiedAt": obj.get("modifiedAt"),
            "modifiedBy": Person.from_dict(obj["modifiedBy"]) if obj.get("modifiedBy") is not None else None,
            "name": obj.get("name"),
            "size": obj.get("size"),
            "title": obj.get("title"),
            "value": obj.get("value")
        })
        return _obj


