# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from alfresco_workflow_client.models.variable import Variable
from typing import Optional, Set
from typing_extensions import Self

class Task(BaseModel):
    """
    A task describes one task for a human user. 
    """ # noqa: E501
    activity_definition_id: Optional[StrictStr] = Field(default=None, description="The activity id of this task", alias="activityDefinitionId")
    assignee: Optional[StrictStr] = Field(default=None, description="The id of the user who is currently assigned this task")
    description: Optional[StrictStr] = Field(default=None, description="The description of this task")
    due_at: Optional[datetime] = Field(default=None, description="The date time this task is due", alias="dueAt")
    duration_in_ms: Optional[StrictInt] = Field(default=None, description="The duration of this task", alias="durationInMs")
    ended_at: Optional[datetime] = Field(default=None, description="The date time this task started", alias="endedAt")
    form_resource_key: Optional[StrictStr] = Field(default=None, description="The key of the form for this task", alias="formResourceKey")
    id: StrictStr = Field(description="The unique id of this task")
    name: Optional[StrictStr] = Field(default=None, description="The text name of this task")
    owner: Optional[StrictStr] = Field(default=None, description="The id of the user who owns this task")
    priority: Optional[StrictInt] = Field(default=None, description="The numeric priority of this task")
    process_definition_id: Optional[StrictStr] = Field(default=None, description="The unique identity of the owning process definition", alias="processDefinitionId")
    process_id: Optional[StrictStr] = Field(default=None, description="The containing process's unique id", alias="processId")
    started_at: Optional[datetime] = Field(default=None, description="The date time this task started", alias="startedAt")
    state: Optional[StrictStr] = Field(default=None, description="The state of this task")
    variables: Optional[List[Variable]] = Field(default=None, description="An array of variables for this task")
    __properties: ClassVar[List[str]] = ["activityDefinitionId", "assignee", "description", "dueAt", "durationInMs", "endedAt", "formResourceKey", "id", "name", "owner", "priority", "processDefinitionId", "processId", "startedAt", "state", "variables"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['unclaimed', 'claimed', 'completed', 'resolved']):
            raise ValueError("must be one of enum values ('unclaimed', 'claimed', 'completed', 'resolved')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Task from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in variables (list)
        _items = []
        if self.variables:
            for _item_variables in self.variables:
                if _item_variables:
                    _items.append(_item_variables.to_dict())
            _dict['variables'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Task from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "activityDefinitionId": obj.get("activityDefinitionId"),
            "assignee": obj.get("assignee"),
            "description": obj.get("description"),
            "dueAt": obj.get("dueAt"),
            "durationInMs": obj.get("durationInMs"),
            "endedAt": obj.get("endedAt"),
            "formResourceKey": obj.get("formResourceKey"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "owner": obj.get("owner"),
            "priority": obj.get("priority"),
            "processDefinitionId": obj.get("processDefinitionId"),
            "processId": obj.get("processId"),
            "startedAt": obj.get("startedAt"),
            "state": obj.get("state"),
            "variables": [Variable.from_dict(_item) for _item in obj["variables"]] if obj.get("variables") is not None else None
        })
        return _obj


