# coding: utf-8

# flake8: noqa
"""
    Alfresco Insight Engine REST API

    **Search SQL API** A Solr SQL passthrough, this feature provides the ability to use SQL to query Solr. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from alfresco_search_sql_client.models.docs_inner import DocsInner
from alfresco_search_sql_client.models.error import Error
from alfresco_search_sql_client.models.error_error import ErrorError
from alfresco_search_sql_client.models.pagination import Pagination
from alfresco_search_sql_client.models.sql_result_set_paging import SQLResultSetPaging
from alfresco_search_sql_client.models.sql_result_set_paging_list import SQLResultSetPagingList
from alfresco_search_sql_client.models.sql_result_set_row_entry import SQLResultSetRowEntry
from alfresco_search_sql_client.models.sql_search_request import SQLSearchRequest
from alfresco_search_sql_client.models.solr_result_set import SolrResultSet
