# coding: utf-8

"""
    Alfresco Content Services REST API

    **Authentication API**  Provides access to the authentication features of Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import alfresco_auth
from .models.ticket_body import TicketBody  # noqa: E501
from alfresco_auth.rest import ApiException


class TestTicketBody(unittest.TestCase):
    """TicketBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTicketBody(self):
        """Test TicketBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = models.ticket_body.TicketBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
