# coding: utf-8

"""
    Alfresco Content Services REST API

    **Discovery API**  Provides access to information about Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_discovery_client.models.status_info import StatusInfo

class TestStatusInfo(unittest.TestCase):
    """StatusInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusInfo:
        """Test StatusInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusInfo`
        """
        model = StatusInfo()
        if include_optional:
            return StatusInfo(
                is_audit_enabled = True,
                is_quick_share_enabled = True,
                is_read_only = True,
                is_thumbnail_generation_enabled = True
            )
        else:
            return StatusInfo(
                is_audit_enabled = True,
                is_quick_share_enabled = True,
                is_read_only = True,
                is_thumbnail_generation_enabled = True,
        )
        """

    def testStatusInfo(self):
        """Test StatusInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
