# coding: utf-8

"""
    Alfresco Content Services REST API

    **Discovery API**  Provides access to information about Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_discovery_client.models.module_info import ModuleInfo

class TestModuleInfo(unittest.TestCase):
    """ModuleInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModuleInfo:
        """Test ModuleInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModuleInfo`
        """
        model = ModuleInfo()
        if include_optional:
            return ModuleInfo(
                description = '',
                id = '',
                install_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                install_state = '',
                title = '',
                version = '',
                version_max = '',
                version_min = ''
            )
        else:
            return ModuleInfo(
        )
        """

    def testModuleInfo(self):
        """Test ModuleInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
