# coding: utf-8

"""
    Alfresco Content Services REST API

    **Discovery API**  Provides access to information about Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_discovery_client.api.discovery_api import DiscoveryApi


class TestDiscoveryApi(unittest.TestCase):
    """DiscoveryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DiscoveryApi()

    def tearDown(self) -> None:
        pass

    def test_get_repository_information(self) -> None:
        """Test case for get_repository_information

        Get repository information
        """
        pass


if __name__ == '__main__':
    unittest.main()
