# coding: utf-8

"""
    Alfresco Content Services REST API

    **Discovery API**  Provides access to information about Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_discovery_client.models.version_info import VersionInfo

class TestVersionInfo(unittest.TestCase):
    """VersionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionInfo:
        """Test VersionInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionInfo`
        """
        model = VersionInfo()
        if include_optional:
            return VersionInfo(
                display = '',
                hotfix = '',
                label = '',
                major = '',
                minor = '',
                patch = '',
                var_schema = 56
            )
        else:
            return VersionInfo(
                display = '',
                hotfix = '',
                label = '',
                major = '',
                minor = '',
                patch = '',
                var_schema = 56,
        )
        """

    def testVersionInfo(self):
        """Test VersionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
