# coding: utf-8

"""
    Alfresco Content Services REST API

    **Discovery API**  Provides access to information about Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_discovery_client.models.entitlements_info import EntitlementsInfo

class TestEntitlementsInfo(unittest.TestCase):
    """EntitlementsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntitlementsInfo:
        """Test EntitlementsInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntitlementsInfo`
        """
        model = EntitlementsInfo()
        if include_optional:
            return EntitlementsInfo(
                is_cluster_enabled = True,
                is_cryptodoc_enabled = True,
                max_docs = 56,
                max_users = 56
            )
        else:
            return EntitlementsInfo(
        )
        """

    def testEntitlementsInfo(self):
        """Test EntitlementsInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
