# coding: utf-8

"""
    Alfresco Insight Engine REST API

    **Search SQL API** A Solr SQL passthrough, this feature provides the ability to use SQL to query Solr.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import alfresco_search-sql
from .api.sql_api import SqlApi  # noqa: E501
from alfresco_search-sql.rest import ApiException


class TestSqlApi(unittest.TestCase):
    """SqlApi unit test stubs"""

    def setUp(self):
        self.api = SqlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search(self):
        """Test case for search

        Alfresco Insight Engine SQL Passthrough  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
