basePath: /alfresco/api/-default-/public/authentication/versions/1
consumes:
- application/json
definitions:
  Error:
    properties:
      error:
        properties:
          briefSummary:
            type: string
          descriptionURL:
            type: string
          errorKey:
            type: string
          logId:
            type: string
          stackTrace:
            type: string
          statusCode:
            format: int32
            type: integer
        type: object
    required:
    - error
    type: object
  Ticket:
    properties:
      id:
        type: string
      userId:
        type: string
    type: object
  TicketBody:
    properties:
      password:
        type: string
      userId:
        type: string
    type: object
  TicketEntry:
    properties:
      entry:
        $ref: '#/definitions/Ticket'
    required:
    - entry
    type: object
  ValidTicket:
    properties:
      id:
        type: string
    type: object
  ValidTicketEntry:
    properties:
      entry:
        $ref: '#/definitions/ValidTicket'
    required:
    - entry
    type: object
info:
  description: '**Authentication API**


    Provides access to the authentication features of Alfresco Content Services.

    '
  title: Alfresco Content Services REST API
  version: '1'
paths:
  /tickets:
    post:
      consumes:
      - application/json
      description: "**Note:** this endpoint is available in Alfresco 5.2 and newer\
        \ versions.\n\nLogs in and returns the new authentication ticket.\n\nThe userId\
        \ and password properties are mandatory in the request body. For example:\n\
        ```JSON\n{\n    \"userId\": \"jbloggs\",\n    \"password\": \"password\"\n\
        }\n```\nTo use the ticket in future requests you should pass it in the request\
        \ header.\nFor example using Javascript:\n  ```Javascript\n    request.setRequestHeader\
        \ (\"Authorization\", \"Basic \" + btoa(ticket));\n  ```\n"
      operationId: createTicket
      parameters:
      - description: The user credential.
        in: body
        name: ticketBodyCreate
        required: true
        schema:
          $ref: '#/definitions/TicketBody'
      produces:
      - application/json
      responses:
        '201':
          description: Successful response
          schema:
            $ref: '#/definitions/TicketEntry'
        '400':
          description: '**userId** or **password** is not provided

            '
        '403':
          description: Login failed
        '501':
          description: SAML is enabled and enforced
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      summary: Create ticket (login)
      tags:
      - authentication
      x-alfresco-since: '5.2'
  /tickets/-me-:
    delete:
      description: '**Note:** this endpoint is available in Alfresco 5.2 and newer
        versions.


        Deletes logged in ticket (logout).

        '
      operationId: deleteTicket
      responses:
        '204':
          description: Successful response
        '400':
          description: URL path does not include **-me-** or the ticket is not provided
            by the Authorization header
        '404':
          description: Status of the user has changed (for example, the user is locked
            or the account is disabled) or the ticket has expired
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      summary: Delete ticket (logout)
      tags:
      - authentication
      x-alfresco-since: '5.2'
    get:
      description: "**Note:** this endpoint is available in Alfresco 5.2 and newer\
        \ versions.\n\nValidates the specified ticket (derived from Authorization\
        \ header) is still valid.\n\nFor example, you can pass the Authorization request\
        \ header using Javascript:\n  ```Javascript\n    request.setRequestHeader\
        \ (\"Authorization\", \"Basic \" + btoa(ticket));\n  ```\n"
      operationId: validateTicket
      produces:
      - application/json
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/ValidTicketEntry'
        '400':
          description: URL path does not include **-me-** or the ticket is not provided
            by the Authorization header
        '401':
          description: Authentication failed
        '404':
          description: The request is authorized correctly but the status of the user
            (of the supplied ticket) has changed (for example, the user is locked
            or the account is disabled) or the ticket has expired
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      summary: Validate ticket
      tags:
      - authentication
      x-alfresco-since: '5.2'
produces:
- application/json
security:
- basicAuth: []
securityDefinitions:
  basicAuth:
    description: HTTP Basic Authentication
    type: basic
swagger: '2.0'
