# generated by datamodel-codegen:
#   filename:  alfresco-discovery.openapi3.yaml
#   timestamp: 2025-06-19T18:36:55+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class EntitlementsInfo(BaseModel):
    isClusterEnabled: Optional[bool] = False
    isCryptodocEnabled: Optional[bool] = False
    maxDocs: Optional[int] = None
    maxUsers: Optional[int] = None


class Error1(BaseModel):
    briefSummary: Optional[str] = None
    descriptionURL: Optional[str] = None
    errorKey: Optional[str] = None
    logId: Optional[str] = None
    stackTrace: Optional[str] = None
    statusCode: Optional[int] = None


class Error(BaseModel):
    error: Error1


class LicenseInfo(BaseModel):
    entitlements: Optional[EntitlementsInfo] = None
    expiresAt: datetime
    holder: str
    issuedAt: datetime
    mode: str
    remainingDays: int


class ModuleInfo(BaseModel):
    description: Optional[str] = None
    id: Optional[str] = None
    installDate: Optional[datetime] = None
    installState: Optional[str] = None
    title: Optional[str] = None
    version: Optional[str] = None
    versionMax: Optional[str] = None
    versionMin: Optional[str] = None


class StatusInfo(BaseModel):
    isAuditEnabled: bool
    isQuickShareEnabled: bool
    isReadOnly: bool
    isThumbnailGenerationEnabled: bool


class VersionInfo(BaseModel):
    display: str
    hotfix: str
    label: str
    major: str
    minor: str
    patch: str
    schema_: int = Field(..., alias="schema")


class RepositoryInfo(BaseModel):
    edition: str
    id: str
    license: Optional[LicenseInfo] = None
    modules: Optional[List[ModuleInfo]] = None
    status: StatusInfo
    version: VersionInfo


class RepositoryEntry(BaseModel):
    repository: RepositoryInfo


class DiscoveryEntry(BaseModel):
    entry: RepositoryEntry
