openapi: 3.0.0
info:
  description: '**Authentication API**
  
  
    Provides access to the authentication features of Alfresco Content Services.
  
    '
  title: Alfresco Content Services REST API
  version: '1'
servers:
  - url: /alfresco/api/-default-/public/authentication/versions/1
security:
  - basicAuth: []
x-original-produces:
  - application/json
x-original-consumes:
  - application/json
components:
  schemas:
    Error:
      properties:
        error:
          properties:
            briefSummary:
              type: string
            descriptionURL:
              type: string
            errorKey:
              type: string
            logId:
              type: string
            stackTrace:
              type: string
            statusCode:
              format: int32
              type: integer
          type: object
      required:
      - error
      type: object
    Ticket:
      properties:
        id:
          type: string
        userId:
          type: string
      type: object
    TicketBody:
      properties:
        password:
          type: string
        userId:
          type: string
      type: object
    TicketEntry:
      properties:
        entry:
          $ref: '#/components/schemas/Ticket'
      required:
      - entry
      type: object
    ValidTicket:
      properties:
        id:
          type: string
      type: object
    ValidTicketEntry:
      properties:
        entry:
          $ref: '#/components/schemas/ValidTicket'
      required:
      - entry
      type: object
  securitySchemes:
    basicAuth:
      scheme: basic
      type: http
paths:
  /tickets:
    post:
      description: "**Note:** this endpoint is available in Alfresco 5.2 and newer versions.\n\
        \nLogs in and returns the new authentication ticket.\n\nThe userId and password\
        \ properties are mandatory in the request body. For example:\n```JSON\n{\n \
        \   \"userId\": \"jbloggs\",\n    \"password\": \"password\"\n}\n```\nTo use\
        \ the ticket in future requests you should pass it in the request header.\n\
        For example using Javascript:\n  ```Javascript\n    request.setRequestHeader\
        \ (\"Authorization\", \"Basic \" + btoa(ticket));\n  ```\n"
      operationId: createTicket
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketBody'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketEntry'
          description: Successful response
        '400':
          description: '**userId** or **password** is not provided
  
            '
        '403':
          description: Login failed
        '501':
          description: SAML is enabled and enforced
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Create ticket (login)
      tags:
      - authentication
      x-alfresco-since: '5.2'
  /tickets/-me-:
    delete:
      description: '**Note:** this endpoint is available in Alfresco 5.2 and newer versions.
  
  
        Deletes logged in ticket (logout).
  
        '
      operationId: deleteTicket
      responses:
        '204':
          description: Successful response
        '400':
          description: URL path does not include **-me-** or the ticket is not provided
            by the Authorization header
        '404':
          description: Status of the user has changed (for example, the user is locked
            or the account is disabled) or the ticket has expired
        default:
          description: Unexpected error
          schema:
            $ref: '#/components/schemas/Error'
      summary: Delete ticket (logout)
      tags:
      - authentication
      x-alfresco-since: '5.2'
    get:
      description: "**Note:** this endpoint is available in Alfresco 5.2 and newer versions.\n\
        \nValidates the specified ticket (derived from Authorization header) is still\
        \ valid.\n\nFor example, you can pass the Authorization request header using\
        \ Javascript:\n  ```Javascript\n    request.setRequestHeader (\"Authorization\"\
        , \"Basic \" + btoa(ticket));\n  ```\n"
      operationId: validateTicket
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidTicketEntry'
          description: Successful response
        '400':
          description: URL path does not include **-me-** or the ticket is not provided
            by the Authorization header
        '401':
          description: Authentication failed
        '404':
          description: The request is authorized correctly but the status of the user
            (of the supplied ticket) has changed (for example, the user is locked or
            the account is disabled) or the ticket has expired
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Validate ticket
      tags:
      - authentication
      x-alfresco-since: '5.2'
