# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.api.audit_api import AuditApi


class TestAuditApi(unittest.TestCase):
    """AuditApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuditApi()

    def tearDown(self) -> None:
        pass

    def test_delete_audit_entries_for_audit_app(self) -> None:
        """Test case for delete_audit_entries_for_audit_app

        Permanently delete audit entries for an audit application
        """
        pass

    def test_delete_audit_entry(self) -> None:
        """Test case for delete_audit_entry

        Permanently delete an audit entry
        """
        pass

    def test_get_audit_app(self) -> None:
        """Test case for get_audit_app

        Get audit application info
        """
        pass

    def test_get_audit_entry(self) -> None:
        """Test case for get_audit_entry

        Get audit entry
        """
        pass

    def test_list_audit_apps(self) -> None:
        """Test case for list_audit_apps

        List audit applications
        """
        pass

    def test_list_audit_entries_for_audit_app(self) -> None:
        """Test case for list_audit_entries_for_audit_app

        List audit entries for an audit application
        """
        pass

    def test_list_audit_entries_for_node(self) -> None:
        """Test case for list_audit_entries_for_node

        List audit entries for a node
        """
        pass

    def test_update_audit_app(self) -> None:
        """Test case for update_audit_app

        Update audit application info
        """
        pass


if __name__ == '__main__':
    unittest.main()
