# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.api.networks_api import NetworksApi


class TestNetworksApi(unittest.TestCase):
    """NetworksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworksApi()

    def tearDown(self) -> None:
        pass

    def test_get_network(self) -> None:
        """Test case for get_network

        Get a network
        """
        pass

    def test_get_network_for_person(self) -> None:
        """Test case for get_network_for_person

        Get network information
        """
        pass

    def test_list_networks_for_person(self) -> None:
        """Test case for list_networks_for_person

        List network membership
        """
        pass


if __name__ == '__main__':
    unittest.main()
