# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.models.child_association_entry import ChildAssociationEntry

class TestChildAssociationEntry(unittest.TestCase):
    """ChildAssociationEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChildAssociationEntry:
        """Test ChildAssociationEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChildAssociationEntry`
        """
        model = ChildAssociationEntry()
        if include_optional:
            return ChildAssociationEntry(
                entry = alfresco_core_client.models.child_association.ChildAssociation(
                    assoc_type = '', 
                    child_id = '', )
            )
        else:
            return ChildAssociationEntry(
                entry = alfresco_core_client.models.child_association.ChildAssociation(
                    assoc_type = '', 
                    child_id = '', ),
        )
        """

    def testChildAssociationEntry(self):
        """Test ChildAssociationEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
