# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.models.site_role_entry import SiteRoleEntry

class TestSiteRoleEntry(unittest.TestCase):
    """SiteRoleEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteRoleEntry:
        """Test SiteRoleEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteRoleEntry`
        """
        model = SiteRoleEntry()
        if include_optional:
            return SiteRoleEntry(
                entry = alfresco_core_client.models.site_role.SiteRole(
                    guid = '', 
                    id = '', 
                    role = 'SiteConsumer', 
                    site = alfresco_core_client.models.site.Site(
                        description = '', 
                        guid = '', 
                        id = '', 
                        preset = '', 
                        role = 'SiteConsumer', 
                        title = '', 
                        visibility = 'PRIVATE', ), )
            )
        else:
            return SiteRoleEntry(
                entry = alfresco_core_client.models.site_role.SiteRole(
                    guid = '', 
                    id = '', 
                    role = 'SiteConsumer', 
                    site = alfresco_core_client.models.site.Site(
                        description = '', 
                        guid = '', 
                        id = '', 
                        preset = '', 
                        role = 'SiteConsumer', 
                        title = '', 
                        visibility = 'PRIVATE', ), ),
        )
        """

    def testSiteRoleEntry(self):
        """Test SiteRoleEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
