# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.models.person_network import PersonNetwork

class TestPersonNetwork(unittest.TestCase):
    """PersonNetwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PersonNetwork:
        """Test PersonNetwork
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonNetwork`
        """
        model = PersonNetwork()
        if include_optional:
            return PersonNetwork(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                home_network = True,
                id = '',
                is_enabled = True,
                paid_network = True,
                quotas = [
                    alfresco_core_client.models.network_quota.NetworkQuota(
                        id = '', 
                        limit = 56, 
                        usage = 56, )
                    ],
                subscription_level = 'Free'
            )
        else:
            return PersonNetwork(
                id = '',
                is_enabled = True,
        )
        """

    def testPersonNetwork(self):
        """Test PersonNetwork"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
