# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.api.people_api import PeopleApi


class TestPeopleApi(unittest.TestCase):
    """PeopleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PeopleApi()

    def tearDown(self) -> None:
        pass

    def test_create_person(self) -> None:
        """Test case for create_person

        Create person
        """
        pass

    def test_delete_avatar_image(self) -> None:
        """Test case for delete_avatar_image

        Delete avatar image
        """
        pass

    def test_get_avatar_image(self) -> None:
        """Test case for get_avatar_image

        Get avatar image
        """
        pass

    def test_get_person(self) -> None:
        """Test case for get_person

        Get a person
        """
        pass

    def test_list_people(self) -> None:
        """Test case for list_people

        List people
        """
        pass

    def test_request_password_reset(self) -> None:
        """Test case for request_password_reset

        Request password reset
        """
        pass

    def test_reset_password(self) -> None:
        """Test case for reset_password

        Reset password
        """
        pass

    def test_update_avatar_image(self) -> None:
        """Test case for update_avatar_image

        Update avatar image
        """
        pass

    def test_update_person(self) -> None:
        """Test case for update_person

        Update person
        """
        pass


if __name__ == '__main__':
    unittest.main()
