# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.models.group_paging import GroupPaging

class TestGroupPaging(unittest.TestCase):
    """GroupPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupPaging:
        """Test GroupPaging
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupPaging`
        """
        model = GroupPaging()
        if include_optional:
            return GroupPaging(
                list = alfresco_core_client.models.group_paging_list.GroupPaging_list(
                    entries = [
                        alfresco_core_client.models.group_entry.GroupEntry(
                            entry = alfresco_core_client.models.group.Group(
                                display_name = '', 
                                id = '', 
                                is_root = True, 
                                parent_ids = [
                                    ''
                                    ], 
                                zones = [
                                    ''
                                    ], ), )
                        ], 
                    pagination = alfresco_core_client.models.pagination.Pagination(
                        count = 56, 
                        has_more_items = True, 
                        max_items = 56, 
                        skip_count = 56, 
                        total_items = 56, ), )
            )
        else:
            return GroupPaging(
        )
        """

    def testGroupPaging(self):
        """Test GroupPaging"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
