# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.models.audit_entry_paging_list import AuditEntryPagingList

class TestAuditEntryPagingList(unittest.TestCase):
    """AuditEntryPagingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuditEntryPagingList:
        """Test AuditEntryPagingList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuditEntryPagingList`
        """
        model = AuditEntryPagingList()
        if include_optional:
            return AuditEntryPagingList(
                entries = [
                    alfresco_core_client.models.audit_entry_entry.AuditEntryEntry(
                        entry = alfresco_core_client.models.audit_entry.AuditEntry(
                            audit_application_id = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            created_by_user = alfresco_core_client.models.user_info.UserInfo(
                                display_name = '', 
                                id = '', ), 
                            id = '', 
                            values = alfresco_core_client.models.values.values(), ), )
                    ],
                pagination = alfresco_core_client.models.pagination.Pagination(
                    count = 56, 
                    has_more_items = True, 
                    max_items = 56, 
                    skip_count = 56, 
                    total_items = 56, )
            )
        else:
            return AuditEntryPagingList(
        )
        """

    def testAuditEntryPagingList(self):
        """Test AuditEntryPagingList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
