# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.models.tag_entry import TagEntry

class TestTagEntry(unittest.TestCase):
    """TagEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagEntry:
        """Test TagEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagEntry`
        """
        model = TagEntry()
        if include_optional:
            return TagEntry(
                entry = alfresco_core_client.models.tag.Tag(
                    count = 1.337, 
                    id = '', 
                    tag = '', )
            )
        else:
            return TagEntry(
                entry = alfresco_core_client.models.tag.Tag(
                    count = 1.337, 
                    id = '', 
                    tag = '', ),
        )
        """

    def testTagEntry(self):
        """Test TagEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
