# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.api.shared_links_api import SharedLinksApi


class TestSharedLinksApi(unittest.TestCase):
    """SharedLinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SharedLinksApi()

    def tearDown(self) -> None:
        pass

    def test_create_shared_link(self) -> None:
        """Test case for create_shared_link

        Create a shared link to a file
        """
        pass

    def test_delete_shared_link(self) -> None:
        """Test case for delete_shared_link

        Deletes a shared link
        """
        pass

    def test_email_shared_link(self) -> None:
        """Test case for email_shared_link

        Email shared link
        """
        pass

    def test_get_shared_link(self) -> None:
        """Test case for get_shared_link

        Get a shared link
        """
        pass

    def test_get_shared_link_content(self) -> None:
        """Test case for get_shared_link_content

        Get shared link content
        """
        pass

    def test_get_shared_link_rendition(self) -> None:
        """Test case for get_shared_link_rendition

        Get shared link rendition information
        """
        pass

    def test_get_shared_link_rendition_content(self) -> None:
        """Test case for get_shared_link_rendition_content

        Get shared link rendition content
        """
        pass

    def test_list_shared_link_renditions(self) -> None:
        """Test case for list_shared_link_renditions

        List renditions for a shared link
        """
        pass

    def test_list_shared_links(self) -> None:
        """Test case for list_shared_links

        List shared links
        """
        pass


if __name__ == '__main__':
    unittest.main()
