# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.models.audit_entry import AuditEntry

class TestAuditEntry(unittest.TestCase):
    """AuditEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuditEntry:
        """Test AuditEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuditEntry`
        """
        model = AuditEntry()
        if include_optional:
            return AuditEntry(
                audit_application_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by_user = alfresco_core_client.models.user_info.UserInfo(
                    display_name = '', 
                    id = '', ),
                id = '',
                values = None
            )
        else:
            return AuditEntry(
                audit_application_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by_user = alfresco_core_client.models.user_info.UserInfo(
                    display_name = '', 
                    id = '', ),
                id = '',
        )
        """

    def testAuditEntry(self):
        """Test AuditEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
