# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_client.models.node_body_move import NodeBodyMove

class TestNodeBodyMove(unittest.TestCase):
    """NodeBodyMove unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeBodyMove:
        """Test NodeBodyMove
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeBodyMove`
        """
        model = NodeBodyMove()
        if include_optional:
            return NodeBodyMove(
                name = '?x!u\'K}qz^sEC)lJ*=-jQ+\'6`%cClu,k\'!\'su[.',
                target_parent_id = ''
            )
        else:
            return NodeBodyMove(
                target_parent_id = '',
        )
        """

    def testNodeBodyMove(self):
        """Test NodeBodyMove"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
