# coding: utf-8

"""
    Alfresco Content Services REST API

    **Model API**  Provides access to the model features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_model_client.api.aspects_api import AspectsApi


class TestAspectsApi(unittest.TestCase):
    """AspectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AspectsApi()

    def tearDown(self) -> None:
        pass

    def test_get_aspect(self) -> None:
        """Test case for get_aspect

        Get an aspect
        """
        pass

    def test_list_aspects(self) -> None:
        """Test case for list_aspects

        List aspects
        """
        pass


if __name__ == '__main__':
    unittest.main()
