# coding: utf-8

"""
    Alfresco Content Services REST API

    **Model API**  Provides access to the model features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_model_client.models.abstract_class_association_source import AbstractClassAssociationSource

class TestAbstractClassAssociationSource(unittest.TestCase):
    """AbstractClassAssociationSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AbstractClassAssociationSource:
        """Test AbstractClassAssociationSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AbstractClassAssociationSource`
        """
        model = AbstractClassAssociationSource()
        if include_optional:
            return AbstractClassAssociationSource(
                cls = '',
                is_mandatory = True,
                is_mandatory_enforced = True,
                is_many = True,
                role = ''
            )
        else:
            return AbstractClassAssociationSource(
        )
        """

    def testAbstractClassAssociationSource(self):
        """Test AbstractClassAssociationSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
