# coding: utf-8

"""
    Alfresco Content Services REST API

    **Discovery API**  Provides access to information about Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import alfresco_discovery
from .api.discovery_api import DiscoveryApi  # noqa: E501
from alfresco_discovery.rest import ApiException


class TestDiscoveryApi(unittest.TestCase):
    """DiscoveryApi unit test stubs"""

    def setUp(self):
        self.api = DiscoveryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_repository_information(self):
        """Test case for get_repository_information

        Get repository information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
