# coding: utf-8

"""
    Alfresco Content Services REST API

    **Discovery API**  Provides access to information about Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import alfresco_discovery
from .models.module_info import ModuleInfo  # noqa: E501
from alfresco_discovery.rest import ApiException


class TestModuleInfo(unittest.TestCase):
    """ModuleInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModuleInfo(self):
        """Test ModuleInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = models.module_info.ModuleInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
