# coding: utf-8

"""
    Alfresco Content Services REST API

    **Discovery API**  Provides access to information about Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import alfresco_discovery
from .models.entitlements_info import EntitlementsInfo  # noqa: E501
from alfresco_discovery.rest import ApiException


class TestEntitlementsInfo(unittest.TestCase):
    """EntitlementsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntitlementsInfo(self):
        """Test EntitlementsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = models.entitlements_info.EntitlementsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
