# coding: utf-8

# flake8: noqa
"""
    Alfresco Content Services REST API

    **Authentication API**  Provides access to the authentication features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from alfresco_auth_client.models.error import Error
from alfresco_auth_client.models.error_error import ErrorError
from alfresco_auth_client.models.ticket import Ticket
from alfresco_auth_client.models.ticket_body import TicketBody
from alfresco_auth_client.models.ticket_entry import TicketEntry
from alfresco_auth_client.models.valid_ticket import ValidTicket
from alfresco_auth_client.models.valid_ticket_entry import ValidTicketEntry
