# coding: utf-8

# flake8: noqa

"""
    Alfresco Insight Engine REST API

    **Search SQL API** A Solr SQL passthrough, this feature provides the ability to use SQL to query Solr. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from alfresco_search_sql_client.api.sql_api import SqlApi

# import ApiClient
from alfresco_search_sql_client.api_response import ApiResponse
from alfresco_search_sql_client.api_client import ApiClient
from alfresco_search_sql_client.configuration import Configuration
from alfresco_search_sql_client.exceptions import OpenApiException
from alfresco_search_sql_client.exceptions import ApiTypeError
from alfresco_search_sql_client.exceptions import ApiValueError
from alfresco_search_sql_client.exceptions import ApiKeyError
from alfresco_search_sql_client.exceptions import ApiAttributeError
from alfresco_search_sql_client.exceptions import ApiException

# import models into sdk package
from alfresco_search_sql_client.models.docs_inner import DocsInner
from alfresco_search_sql_client.models.error import Error
from alfresco_search_sql_client.models.error_error import ErrorError
from alfresco_search_sql_client.models.pagination import Pagination
from alfresco_search_sql_client.models.sql_result_set_paging import SQLResultSetPaging
from alfresco_search_sql_client.models.sql_result_set_paging_list import SQLResultSetPagingList
from alfresco_search_sql_client.models.sql_result_set_row_entry import SQLResultSetRowEntry
from alfresco_search_sql_client.models.sql_search_request import SQLSearchRequest
from alfresco_search_sql_client.models.solr_result_set import SolrResultSet
