# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Download(BaseModel):
    """
    Download
    """ # noqa: E501
    bytes_added: Optional[StrictInt] = Field(default=None, description="number of bytes added so far in the zip", alias="bytesAdded")
    files_added: Optional[StrictInt] = Field(default=None, description="number of files added so far in the zip", alias="filesAdded")
    id: Optional[StrictStr] = Field(default=None, description="the id of the download node")
    status: Optional[StrictStr] = Field(default='PENDING', description="the current status of the download node creation")
    total_bytes: Optional[StrictInt] = Field(default=None, description="the total number of bytes to be added in the zip", alias="totalBytes")
    total_files: Optional[StrictInt] = Field(default=None, description="the total number of files to be added in the zip", alias="totalFiles")
    __properties: ClassVar[List[str]] = ["bytesAdded", "filesAdded", "id", "status", "totalBytes", "totalFiles"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PENDING', 'CANCELLED', 'IN_PROGRESS', 'DONE', 'MAX_CONTENT_SIZE_EXCEEDED']):
            raise ValueError("must be one of enum values ('PENDING', 'CANCELLED', 'IN_PROGRESS', 'DONE', 'MAX_CONTENT_SIZE_EXCEEDED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Download from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Download from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bytesAdded": obj.get("bytesAdded"),
            "filesAdded": obj.get("filesAdded"),
            "id": obj.get("id"),
            "status": obj.get("status") if obj.get("status") is not None else 'PENDING',
            "totalBytes": obj.get("totalBytes"),
            "totalFiles": obj.get("totalFiles")
        })
        return _obj


