# generated by datamodel-codegen:
#   filename:  alfresco-auth.yaml
#   timestamp: 2025-06-23T07:22:14+00:00

from __future__ import annotations

from pydantic import BaseModel


class Error1(BaseModel):
    briefSummary: str | None = None
    descriptionURL: str | None = None
    errorKey: str | None = None
    logId: str | None = None
    stackTrace: str | None = None
    statusCode: int | None = None


class Error(BaseModel):
    error: Error1


class Ticket(BaseModel):
    id: str | None = None
    userId: str | None = None


class TicketBody(BaseModel):
    password: str | None = None
    userId: str | None = None


class TicketEntry(BaseModel):
    entry: Ticket


class ValidTicket(BaseModel):
    id: str | None = None


class ValidTicketEntry(BaseModel):
    entry: ValidTicket
