# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import alfresco_core
from .models.node_body_create import NodeBodyCreate  # noqa: E501
from alfresco_core.rest import ApiException


class TestNodeBodyCreate(unittest.TestCase):
    """NodeBodyCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeBodyCreate(self):
        """Test NodeBodyCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = models.node_body_create.NodeBodyCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
