# coding: utf-8

# flake8: noqa

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from alfresco_workflow_client.api.deployments_api import DeploymentsApi
from alfresco_workflow_client.api.process_definitions_api import ProcessDefinitionsApi
from alfresco_workflow_client.api.processes_api import ProcessesApi
from alfresco_workflow_client.api.tasks_api import TasksApi

# import ApiClient
from alfresco_workflow_client.api_response import ApiResponse
from alfresco_workflow_client.api_client import ApiClient
from alfresco_workflow_client.configuration import Configuration
from alfresco_workflow_client.exceptions import OpenApiException
from alfresco_workflow_client.exceptions import ApiTypeError
from alfresco_workflow_client.exceptions import ApiValueError
from alfresco_workflow_client.exceptions import ApiKeyError
from alfresco_workflow_client.exceptions import ApiAttributeError
from alfresco_workflow_client.exceptions import ApiException

# import models into sdk package
from alfresco_workflow_client.models.candidate import Candidate
from alfresco_workflow_client.models.candidate_entry import CandidateEntry
from alfresco_workflow_client.models.candidate_paging import CandidatePaging
from alfresco_workflow_client.models.candidate_paging_list import CandidatePagingList
from alfresco_workflow_client.models.company import Company
from alfresco_workflow_client.models.deployment import Deployment
from alfresco_workflow_client.models.deployment_entry import DeploymentEntry
from alfresco_workflow_client.models.deployment_paging import DeploymentPaging
from alfresco_workflow_client.models.deployment_paging_list import DeploymentPagingList
from alfresco_workflow_client.models.error import Error
from alfresco_workflow_client.models.error_error import ErrorError
from alfresco_workflow_client.models.item import Item
from alfresco_workflow_client.models.item_body import ItemBody
from alfresco_workflow_client.models.item_entry import ItemEntry
from alfresco_workflow_client.models.item_paging import ItemPaging
from alfresco_workflow_client.models.item_paging_list import ItemPagingList
from alfresco_workflow_client.models.pagination import Pagination
from alfresco_workflow_client.models.person import Person
from alfresco_workflow_client.models.process import Process
from alfresco_workflow_client.models.process_body import ProcessBody
from alfresco_workflow_client.models.process_body_variable import ProcessBodyVariable
from alfresco_workflow_client.models.process_definition import ProcessDefinition
from alfresco_workflow_client.models.process_definition_entry import ProcessDefinitionEntry
from alfresco_workflow_client.models.process_definition_paging import ProcessDefinitionPaging
from alfresco_workflow_client.models.process_definition_paging_list import ProcessDefinitionPagingList
from alfresco_workflow_client.models.process_entry import ProcessEntry
from alfresco_workflow_client.models.process_paging import ProcessPaging
from alfresco_workflow_client.models.process_paging_list import ProcessPagingList
from alfresco_workflow_client.models.task import Task
from alfresco_workflow_client.models.task_body import TaskBody
from alfresco_workflow_client.models.task_entry import TaskEntry
from alfresco_workflow_client.models.task_form_model import TaskFormModel
from alfresco_workflow_client.models.task_form_model_entry import TaskFormModelEntry
from alfresco_workflow_client.models.task_form_model_paging import TaskFormModelPaging
from alfresco_workflow_client.models.task_form_model_paging_list import TaskFormModelPagingList
from alfresco_workflow_client.models.task_paging import TaskPaging
from alfresco_workflow_client.models.task_paging_list import TaskPagingList
from alfresco_workflow_client.models.variable import Variable
from alfresco_workflow_client.models.variable_body import VariableBody
from alfresco_workflow_client.models.variable_entry import VariableEntry
from alfresco_workflow_client.models.variable_paging import VariablePaging
from alfresco_workflow_client.models.variable_paging_list import VariablePagingList
