# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_search_client.models.search_entry import SearchEntry

class TestSearchEntry(unittest.TestCase):
    """SearchEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchEntry:
        """Test SearchEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchEntry`
        """
        model = SearchEntry()
        if include_optional:
            return SearchEntry(
                highlight = [
                    alfresco_search_client.models.search_entry_highlight_inner.SearchEntry_highlight_inner(
                        field = '', 
                        snippets = [
                            ''
                            ], )
                    ],
                score = 1.337
            )
        else:
            return SearchEntry(
        )
        """

    def testSearchEntry(self):
        """Test SearchEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
