# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_search_client.models.request_filter_queries_inner import RequestFilterQueriesInner

class TestRequestFilterQueriesInner(unittest.TestCase):
    """RequestFilterQueriesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestFilterQueriesInner:
        """Test RequestFilterQueriesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestFilterQueriesInner`
        """
        model = RequestFilterQueriesInner()
        if include_optional:
            return RequestFilterQueriesInner(
                query = '',
                tags = [
                    ''
                    ]
            )
        else:
            return RequestFilterQueriesInner(
        )
        """

    def testRequestFilterQueriesInner(self):
        """Test RequestFilterQueriesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
