# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_search_client.models.request_facet_intervals import RequestFacetIntervals

class TestRequestFacetIntervals(unittest.TestCase):
    """RequestFacetIntervals unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestFacetIntervals:
        """Test RequestFacetIntervals
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestFacetIntervals`
        """
        model = RequestFacetIntervals()
        if include_optional:
            return RequestFacetIntervals(
                intervals = [
                    alfresco_search_client.models.request_facet_intervals_intervals_inner.RequestFacetIntervals_intervals_inner(
                        field = '', 
                        label = '', 
                        sets = [
                            alfresco_search_client.models.request_facet_set.RequestFacetSet(
                                end = '', 
                                end_inclusive = True, 
                                label = '', 
                                start = '', 
                                start_inclusive = True, )
                            ], )
                    ],
                sets = [
                    alfresco_search_client.models.request_facet_set.RequestFacetSet(
                        end = '', 
                        end_inclusive = True, 
                        label = '', 
                        start = '', 
                        start_inclusive = True, )
                    ]
            )
        else:
            return RequestFacetIntervals(
        )
        """

    def testRequestFacetIntervals(self):
        """Test RequestFacetIntervals"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
