# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_search_client.models.request_pagination import RequestPagination

class TestRequestPagination(unittest.TestCase):
    """RequestPagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestPagination:
        """Test RequestPagination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestPagination`
        """
        model = RequestPagination()
        if include_optional:
            return RequestPagination(
                max_items = 1,
                skip_count = 0
            )
        else:
            return RequestPagination(
        )
        """

    def testRequestPagination(self):
        """Test RequestPagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
