# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.models.item_paging_list import ItemPagingList

class TestItemPagingList(unittest.TestCase):
    """ItemPagingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemPagingList:
        """Test ItemPagingList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemPagingList`
        """
        model = ItemPagingList()
        if include_optional:
            return ItemPagingList(
                entries = [
                    alfresco_workflow_client.models.item_entry.ItemEntry(
                        entry = alfresco_workflow_client.models.item.Item(
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            created_by = alfresco_workflow_client.models.person.Person(
                                avatar_id = '', 
                                company = alfresco_workflow_client.models.company.Company(
                                    address1 = '', 
                                    address2 = '', 
                                    address3 = '', 
                                    email = '', 
                                    fax = '', 
                                    organization = '', 
                                    postcode = '', 
                                    telephone = '', ), 
                                description = '', 
                                email = '', 
                                email_notifications_enabled = True, 
                                enabled = True, 
                                first_name = '', 
                                google_id = '', 
                                id = '', 
                                instant_message_id = '', 
                                job_title = '', 
                                last_name = '', 
                                location = '', 
                                mobile = '', 
                                skype_id = '', 
                                status_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                telephone = '', 
                                user_status = '', ), 
                            description = '', 
                            edited = True, 
                            id = '', 
                            mime_type = '', 
                            modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            modified_by = alfresco_workflow_client.models.person.Person(
                                avatar_id = '', 
                                description = '', 
                                email = '', 
                                email_notifications_enabled = True, 
                                enabled = True, 
                                first_name = '', 
                                google_id = '', 
                                id = '', 
                                instant_message_id = '', 
                                job_title = '', 
                                last_name = '', 
                                location = '', 
                                mobile = '', 
                                skype_id = '', 
                                status_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                telephone = '', 
                                user_status = '', ), 
                            name = '', 
                            size = 56, 
                            title = '', 
                            value = 56, ), )
                    ],
                pagination = alfresco_workflow_client.models.pagination.Pagination(
                    count = 56, 
                    has_more_items = True, 
                    max_items = 56, 
                    skip_count = 56, 
                    total_items = 56, )
            )
        else:
            return ItemPagingList(
        )
        """

    def testItemPagingList(self):
        """Test ItemPagingList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
