# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.models.task_body import TaskBody

class TestTaskBody(unittest.TestCase):
    """TaskBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskBody:
        """Test TaskBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskBody`
        """
        model = TaskBody()
        if include_optional:
            return TaskBody(
                description = '',
                due_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                owner = '',
                priority = 56,
                state = 'unclaimed',
                variables = [
                    alfresco_workflow_client.models.variable.Variable(
                        name = '', 
                        scope = '', 
                        type = '', 
                        value = 56, )
                    ]
            )
        else:
            return TaskBody(
        )
        """

    def testTaskBody(self):
        """Test TaskBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
