# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.api.deployments_api import DeploymentsApi


class TestDeploymentsApi(unittest.TestCase):
    """DeploymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeploymentsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_deployment(self) -> None:
        """Test case for delete_deployment

        Delete a deployment
        """
        pass

    def test_get_deployment(self) -> None:
        """Test case for get_deployment

        Get a deployment
        """
        pass

    def test_list_deployments(self) -> None:
        """Test case for list_deployments

        List deployments
        """
        pass


if __name__ == '__main__':
    unittest.main()
