# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_create_task_item(self) -> None:
        """Test case for create_task_item

        Create an item
        """
        pass

    def test_create_task_variables(self) -> None:
        """Test case for create_task_variables

        Create or update variables
        """
        pass

    def test_delete_task_item(self) -> None:
        """Test case for delete_task_item

        Delete an item
        """
        pass

    def test_delete_task_variable(self) -> None:
        """Test case for delete_task_variable

        Delete a variable
        """
        pass

    def test_get_task(self) -> None:
        """Test case for get_task

        Get a task
        """
        pass

    def test_get_task_form_model(self) -> None:
        """Test case for get_task_form_model

        Get a task form model
        """
        pass

    def test_list_task_candidates(self) -> None:
        """Test case for list_task_candidates

        List task candidates
        """
        pass

    def test_list_task_items(self) -> None:
        """Test case for list_task_items

        List items
        """
        pass

    def test_list_task_variables(self) -> None:
        """Test case for list_task_variables

        List variables
        """
        pass

    def test_list_tasks(self) -> None:
        """Test case for list_tasks

        List tasks
        """
        pass

    def test_list_tasks_for_process(self) -> None:
        """Test case for list_tasks_for_process

        List tasks for a process
        """
        pass

    def test_update_task(self) -> None:
        """Test case for update_task

        Update a task
        """
        pass

    def test_update_task_variable(self) -> None:
        """Test case for update_task_variable

        Create or update a variable
        """
        pass


if __name__ == '__main__':
    unittest.main()
