# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.models.person import Person

class TestPerson(unittest.TestCase):
    """Person unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Person:
        """Test Person
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Person`
        """
        model = Person()
        if include_optional:
            return Person(
                avatar_id = '',
                company = alfresco_workflow_client.models.company.Company(
                    address1 = '', 
                    address2 = '', 
                    address3 = '', 
                    email = '', 
                    fax = '', 
                    organization = '', 
                    postcode = '', 
                    telephone = '', ),
                description = '',
                email = '',
                email_notifications_enabled = True,
                enabled = True,
                first_name = '',
                google_id = '',
                id = '',
                instant_message_id = '',
                job_title = '',
                last_name = '',
                location = '',
                mobile = '',
                skype_id = '',
                status_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                telephone = '',
                user_status = ''
            )
        else:
            return Person(
                id = '',
        )
        """

    def testPerson(self):
        """Test Person"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
