# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.models.task_form_model_paging import TaskFormModelPaging

class TestTaskFormModelPaging(unittest.TestCase):
    """TaskFormModelPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskFormModelPaging:
        """Test TaskFormModelPaging
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskFormModelPaging`
        """
        model = TaskFormModelPaging()
        if include_optional:
            return TaskFormModelPaging(
                list = alfresco_workflow_client.models.task_form_model_paging_list.TaskFormModelPaging_list(
                    entries = [
                        alfresco_workflow_client.models.task_form_model_entry.TaskFormModelEntry(
                            entry = alfresco_workflow_client.models.task_form_model.TaskFormModel(
                                allowed_values = [
                                    ''
                                    ], 
                                data_type = '', 
                                default_value = '', 
                                name = '', 
                                qualified_name = '', 
                                required = True, 
                                title = '', ), )
                        ], 
                    pagination = alfresco_workflow_client.models.pagination.Pagination(
                        count = 56, 
                        has_more_items = True, 
                        max_items = 56, 
                        skip_count = 56, 
                        total_items = 56, ), )
            )
        else:
            return TaskFormModelPaging(
        )
        """

    def testTaskFormModelPaging(self):
        """Test TaskFormModelPaging"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
