# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.models.process_entry import ProcessEntry

class TestProcessEntry(unittest.TestCase):
    """ProcessEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessEntry:
        """Test ProcessEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessEntry`
        """
        model = ProcessEntry()
        if include_optional:
            return ProcessEntry(
                entry = alfresco_workflow_client.models.process.Process(
                    business_key = '', 
                    delete_reason = '', 
                    duration_in_ms = 56, 
                    end_activity_definition_id = '', 
                    ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    id = '', 
                    process_definition_id = '', 
                    start_activity_definition_id = '', 
                    start_user_id = '', 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return ProcessEntry(
        )
        """

    def testProcessEntry(self):
        """Test ProcessEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
