# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.models.candidate_paging import CandidatePaging

class TestCandidatePaging(unittest.TestCase):
    """CandidatePaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CandidatePaging:
        """Test CandidatePaging
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CandidatePaging`
        """
        model = CandidatePaging()
        if include_optional:
            return CandidatePaging(
                list = alfresco_workflow_client.models.candidate_paging_list.CandidatePaging_list(
                    entries = [
                        alfresco_workflow_client.models.candidate_entry.CandidateEntry(
                            entry = alfresco_workflow_client.models.candidate.Candidate(
                                candidate_id = '', 
                                candidate_type = 'user', ), )
                        ], 
                    pagination = alfresco_workflow_client.models.pagination.Pagination(
                        count = 56, 
                        has_more_items = True, 
                        max_items = 56, 
                        skip_count = 56, 
                        total_items = 56, ), )
            )
        else:
            return CandidatePaging(
        )
        """

    def testCandidatePaging(self):
        """Test CandidatePaging"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
