# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.models.task_form_model import TaskFormModel

class TestTaskFormModel(unittest.TestCase):
    """TaskFormModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskFormModel:
        """Test TaskFormModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskFormModel`
        """
        model = TaskFormModel()
        if include_optional:
            return TaskFormModel(
                allowed_values = [
                    ''
                    ],
                data_type = '',
                default_value = '',
                name = '',
                qualified_name = '',
                required = True,
                title = ''
            )
        else:
            return TaskFormModel(
        )
        """

    def testTaskFormModel(self):
        """Test TaskFormModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
