# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.models.process_paging import ProcessPaging

class TestProcessPaging(unittest.TestCase):
    """ProcessPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessPaging:
        """Test ProcessPaging
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessPaging`
        """
        model = ProcessPaging()
        if include_optional:
            return ProcessPaging(
                list = alfresco_workflow_client.models.process_paging_list.ProcessPaging_list(
                    entries = [
                        alfresco_workflow_client.models.process_entry.ProcessEntry(
                            entry = alfresco_workflow_client.models.process.Process(
                                business_key = '', 
                                delete_reason = '', 
                                duration_in_ms = 56, 
                                end_activity_definition_id = '', 
                                ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                id = '', 
                                process_definition_id = '', 
                                start_activity_definition_id = '', 
                                start_user_id = '', 
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                        ], 
                    pagination = alfresco_workflow_client.models.pagination.Pagination(
                        count = 56, 
                        has_more_items = True, 
                        max_items = 56, 
                        skip_count = 56, 
                        total_items = 56, ), )
            )
        else:
            return ProcessPaging(
        )
        """

    def testProcessPaging(self):
        """Test ProcessPaging"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
