# coding: utf-8

"""
    Alfresco Content Services REST API

    **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_workflow_client.models.task_entry import TaskEntry

class TestTaskEntry(unittest.TestCase):
    """TaskEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskEntry:
        """Test TaskEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskEntry`
        """
        model = TaskEntry()
        if include_optional:
            return TaskEntry(
                entry = alfresco_workflow_client.models.task.Task(
                    activity_definition_id = '', 
                    assignee = '', 
                    description = '', 
                    due_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    duration_in_ms = 56, 
                    ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    form_resource_key = '', 
                    id = '', 
                    name = '', 
                    owner = '', 
                    priority = 56, 
                    process_definition_id = '', 
                    process_id = '', 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    state = 'unclaimed', 
                    variables = [
                        alfresco_workflow_client.models.variable.Variable(
                            name = '', 
                            scope = '', 
                            type = '', 
                            value = 56, )
                        ], )
            )
        else:
            return TaskEntry(
        )
        """

    def testTaskEntry(self):
        """Test TaskEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
